### ISSUE TITLE
Suitarr Image Changes

### ISSUE THREAD

**Issue by desimaniac** [andrewkhunn/suitarr_mp4_automator#1]
Hotio has updated his images to use a slightly different format (eg `hotio/suitarr:sonarr` to `hotio/sonarr`). Will you be updating this as well?

**Comment by andrewkhunn** [comment]
Done.

Thanks for the head's up!

**Comment by desimaniac** [comment]
Let me know if you plan on switching your images to the same format as his... Thanks.
